export const EXAMPLE_ADD = 'EXAMPLE_ADD'
export const EXAMPLE_EDIT = 'EXAMPLE_EDIT'
export const EXAMPLE_DELETE = 'EXAMPLE_DELETE'

export const USER = 'USER'
export const USER_PENDING = 'USER_PENDING'
export const USER_REJECTED = 'USER_REJECTED'
export const USER_FULFILLED = 'USER_FULFILLED'