export const EXAMPLE_ADD = 'EXAMPLE_ADD'
export const EXAMPLE_EDIT = 'EXAMPLE_EDIT'
export const EXAMPLE_DELETE = 'EXAMPLE_DELETE'

export const USER = 'USER'
export const USER_PENDING = 'USER_PENDING'
export const USER_REJECTED = 'USER_REJECTED'
export const USER_FULFILLED = 'USER_FULFILLED'


export const QUESTION = 'QUESTION'
export const QUESTION_PENDING = 'QUESTION_PENDING'
export const QUESTION_REJECTED = 'QUESTION_REJECTED'
export const QUESTION_FULFILLED = 'QUESTION_FULFILLED'

export const ADD_ANSWER = "ADD_ANSWER"

export const SUBMIT_ANSWER = "SUBMIT_ANSWER"
export const SUBMIT_ANSWER_PENDING = "SUBMIT_ANSWER_PENDING"
export const SUBMIT_ANSWER_REJECTED = "SUBMIT_ANSWER_REJECTED"
export const SUBMIT_ANSWER_FULFILLED = "SUBMIT_ANSWER_FULFILLED"